name: Auto Merge to QAAutomatico

on:
  pull_request:
    branches:
      - Desarrollo
    types:
      - closed

jobs:
  merge-to-qa:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to QAAutomatico
      run: |
        git checkout QAAutomatico
        git merge Desarrollo
        git push origin QAAutomatico
